# Datenstrom Yellow extension settings

Extension: Cloudfiles
Version: 0.3.0
Description: List the files of a shared cloud folder.
Developer: Liam Perlaki
Tag: feature
DownloadUrl: https://github.com/pfadfinder26/yellow-cloudfiles/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/pfadfinder26/yellow-cloudfiles
DocumentationLanguage: en, de
Published: 2026-09-28 12:51:48
Status: experimental
system/workers/cloudfiles.php: cloudfiles.php, create, update
